### ISSUE TITLE
Issue when trying to retrieve a specific version of `HGNC`

### ISSUE THREAD

**Issue by DimitrisAlivas** [pyobo/pyobo#136]
` pyobo.get_xrefs_df('hgnc', version='2022-10-01')`

Changing the `version` parameter to retrieve a different version of HGNC, does not result in a change in what is being downloaded by pyobo.

Potential cause: it’s not properly passing the version through to the HGNC loader function (this is a more general issue that any custom PyOBO loaders don't get the desired version passed through)

Related screenshot from debugging:

![Screenshot 2022-11-17 at 15 33 01 (1)](https://user-images.githubusercontent.com/18250976/203038089-84779332-8389-4c05-b3d4-7eb9b68846f3.png)

**Comment by cthoyt** [comment]
Should be fixed by e68544a
