### ISSUE TITLE
FTP error when downloading PFAM

### ISSUE THREAD

**Issue by cmungall** [pyobo/pyobo#139]
```python
>>> import pyobo.sources.pfam as pfam
>>> obo=pfam.get_obo()
>>> obo.write_obo("pfam.obo")
INFO: [2023-01-11 13:02:11] pystow.utils - downloading with urllib from ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.clans.tsv.gz to /Users/cjm/.data/pyobo/raw/pfam/35.0/Pfam-A.clans.tsv.gz
Traceback (most recent call last):
...
urllib.error.URLError: <urlopen error ftp error: error_reply('229 Extended Passive Mode Entered (|||24513|)')>
```

The file itself appears to be fine:

```
✗ curl -L -s ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.clans.tsv.gz | gzip -dc | head
PF00001	CL0192	GPCR_A	7tm_1	7 transmembrane receptor (rhodopsin family)
PF00002	CL0192	GPCR_A	7tm_2	7 transmembrane receptor (Secretin family)
PF00003	CL0192	GPCR_A	7tm_3	7 transmembrane sweet-taste receptor of 3 GCPR
PF00004	CL0023	P-loop_NTPase	AAA	ATPase family associated with various cellular activities (AAA)
PF00005	CL0023	P-loop_NTPase	ABC_tran	ABC transporter
PF00006	CL0023	P-loop_NTPase	ATP-synt_ab	ATP synthase alpha/beta family, nucleotide-binding domain
PF00007	CL0079	Cystine-knot	Cys_knot	Cystine-knot domain
PF00008	CL0001	EGF	EGF	EGF-like domain
PF00009	CL0023	P-loop_NTPase	GTP_EFTU	Elongation factor Tu GTP binding domain
PF00010			HLH	Helix-loop-helix DNA-binding domain
```

FWIW, I think any EBI FTP URL can be substituted with an HTTP URL, which may be more robust, e.g. http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.clans.tsv.gz

**Comment by cthoyt** [comment]
Sometimes the EBI FTP server bugs out because of too many active connections. I'm not super familiar with `229 Extended Passive Mode Entered (|||24513|)` but did you try this again after waiting some time and get the same error? I'm aware you can access these data with HTTP or HTTPS but also found download times are an order of magnitude slower so would rather not switch over

**Comment by cmungall** [comment]
huh, there you go, it works now. I did try this a few times interspersed with curl, guess I was unlucky!

@kltm - we also analyzed the EBI ftp vs http, did we come to the same conclusion?

**Comment by kltm** [comment]
@cmungall Similar. Our ongoing issues are here: https://github.com/geneontology/pipeline/issues/305
For example:
```
https://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 4.5KB/s
http://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 15.0MB/s
ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl ~ 20.0MB/s
```
We switched away from FTP in the first place due to reliability issues with their FTP (https://github.com/geneontology/pipeline/issues/304).
