### ISSUE TITLE
`pyobo.get_sssom_df()` for UMLS returns `prefix:PREFIX:ID`

### ISSUE THREAD

**Issue by hrshdhgd** [pyobo/pyobo#155]
Firstly, @cthoyt , thank you so much for adding the `names` flag to `pyobo.get_sssom_df()`. This sped up the process significantly!

When I run
```
df = pyobo.get_sssom_df("umls", names=False)
``` 
I get a mappings file. Now some of the rows look like below

| subject_id | object_id    | predicate_id       | mapping_justification |
|------------|--------------|--------------------|-----------------------|
| umls:C0000184 | go:GO:0004113 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |
| umls:C0000184 | go:GO:0008663 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |
| umls:C0000727 | hp:HP:0033400 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |
| umls:C0000729 | hp:HP:0032155 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |
| umls:C0242987  | hgnc:HGNC:11796 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |
| umls:C0242988  | hgnc:HGNC:11799 | oboinowl:hasDbXref | sempav:UnspecifiedMatching |

As you can see `HP:` is `hp:HP:XXX` and it is the same for `GO` and `HGNC`.

 I tried using `curies` 

```
obo_converter = curies.get_obo_converter()
obo_converter.pd_standardize_curie(df, column="object_id")
```

But that doesn't seem to work. Is there something that can be done in `pyobo` itself?  It is an easy string replace but a generalized solution may be better?

**Comment by cthoyt** [comment]
@hrshdhgd this might be due to updates in the underlying UMLS data that now includes bananas. I have instituted a more general fix that handles bananas proactively in #156.
