### ISSUE TITLE
NCIT has a genome nomenclature! AHHH!!

### ISSUE THREAD

**Issue by cthoyt** [pyobo/pyobo#24]
Reuse code from INDRA (https://github.com/sorgerlab/indra/blob/master/indra/resources/update_resources.py#L460-L524)

**Comment by bgyori** [comment]
Not sure if you've seen this already but NCIT provides downloadable mappings to HGNC, UP, GO and CHEBI, and I wrote some code in INDRA to process those:
https://github.com/sorgerlab/indra/blob/master/indra/resources/update_resources.py#L460-L524
Would adapting this work?
