### ISSUE TITLE
SCHEM

### ISSUE THREAD

**Issue by cthoyt** [pyobo/pyobo#27]
https://github.com/OpenBEL/resource-generator/blob/master/datasets/selventa-legacy-chemical-names.txt

**Comment by bgyori** [comment]
Would adapting this block of code more or less solve this?
https://github.com/sorgerlab/indra/blob/master/indra/resources/update_resources.py#L291-L354

**Comment by cthoyt** [comment]
Partially. In general, there are quiet a few resources still using SCHEM, so having this fully integrated (with terms as well) would be advantageous. I didn't realize until I read these again that there were actually internal Selventa accession numbers for all of these entities
