### ISSUE TITLE
Get more careful about relations between genes, RNAs, and proteins

### ISSUE THREAD

**Issue by cthoyt** [pyobo/pyobo#54]
Very similar to #39

- [ ] make sure xrefs in HGNC to proteins and protein families aren't pointing towards RNAs or genes (make separate relationship)

**Comment by cthoyt** [comment]
Asked this on twitter:

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">What’s the correct relationship between a gene e.g. hgnc:6863 (MAP4K1 ) and an enzyme code (eccode:2.7.11.1) to which its translated protein is a member?<br><br>I want a single relation for chain of RO:0002204 (gene product of) then isA. Does that make sense?<a href="https://twitter.com/chrismungall?ref_src=twsrc%5Etfw">@chrismungall</a> <a href="https://twitter.com/genenames?ref_src=twsrc%5Etfw">@genenames</a></p>&mdash; Charles Tapley Hoyt (@cthoyt) <a href="https://twitter.com/cthoyt/status/1262139075181543425?ref_src=twsrc%5Etfw">May 17, 2020</a></blockquote>

**Comment by bgyori** [comment]
I'd say, having two separate relations with the UniProt node in between would be a pretty good solution here. Is it necessary for some reason to collapse this into a single relation?
