### ISSUE TITLE
Issues with ChEBML mappings

### ISSUE THREAD

**Issue by bgyori** [pyobo/pyobo#65]
I was trying the following code:
```
import pyobo
c2d = pyobo.get_filtered_xrefs('chembl', 'drugbank')
d2c = pyobo.get_filtered_xrefs('drugbank', 'chembl')
```
The first (c2d) line errors with:
```
pyobo/getters.py in _ensure_obo_path(prefix)
    100     entry = obofoundry.get(prefix)
    101     if entry is None:
--> 102         raise NoOboFoundry(f'OBO Foundry is missing the prefix: {prefix}')
    103 
    104     build = entry.get('build')

NoOboFoundry: OBO Foundry is missing the prefix: chembl
```
and the second (d2c) line runs for a really long time, displaying the below tqdm 4 times (with delays in between), and then returns an empty dict:
```
Drugs: 100%|██████████████████████████████████████████████████| 13563/13563 [00:09<00:00, 1375.53it/s]
Drugs: 100%|██████████████████████████████████████████████████| 13563/13563 [00:05<00:00, 2403.18it/s]
Drugs: 100%|██████████████████████████████████████████████████| 13563/13563 [00:05<00:00, 2541.94it/s]
Drugs: 100%|██████████████████████████████████████████████████| 13563/13563 [00:06<00:00, 2151.38it/s]
```

It's not totally obvious to me what the underlying issues are here but with some guidance I can try to solve them.

**Comment by cthoyt** [comment]
There's no entry OBO Foundry for ChEMBL. This message would probably be more helpful if it said it's not available in OBO Foundry, an alternate OBO source hasn't been curated in the metaregistry, and I haven't written an extractor for it.

However, there are mappings to chembl from drugbank if I recall. This function only goes one direction, so there's a `flip` argument for convenience. You can do:

```python
import pyobo
c2d = pyobo.get_filtered_xrefs('drugbank', 'chembl', flip=True)
d2c = pyobo.get_filtered_xrefs('drugbank', 'chembl')
```

Or you can wait for https://github.com/pyobo/pyobo/pull/61 which I will finish... eventually

**Comment by cthoyt** [comment]
Oh, also, chembl is not a preferred namespace. Either use [`chembl.compound`](https://registry.identifiers.org/registry/chembl.compound#!) or [`chembl.target`](https://registry.identifiers.org/registry/chembl.target)

**Comment by bgyori** [comment]
Thanks, `chembl.compound` worked! We recently worked on integrating some information from ChEBML and it involved spinning up an sqlite instance based on their DB dump (ftp://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBLdb/latest/). I assume that approach could work for OBO-ifying the content for pyobo as well. We can contribute some code for that if you think that's the right approach.
