### ISSUE TITLE
pyobo.get_name() returning None

### ISSUE THREAD

**Issue by aren-lorenson-enveda** [pyobo/pyobo#70]
`pyobo.get_name('ncbitaxon','52818')` used to return `'Allamanda cathartica'` ([link](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi)) & now it is `None`. 

I've rebuilt the `~/.obo/` caches on 0.2.7.dev0 & tried `get_name` on `0.2.6` & `0.2.4` as well.

**Comment by cthoyt** [comment]
Hey @aren-lorenson-enveda thanks for pointing this out. I found that there was a typo in the `get_primary_identifier()` function that was causing this to return none instead of using the original identifier for nomenclatures that don't list any alternative identifiers at all. Fix coming in #74
