### ISSUE TITLE
Add alt_id support

### ISSUE THREAD

**Issue by cthoyt** [pyobo/pyobo#8]
Alt IDs are already part of the node's data structure provided by `obonet`

- [x] Add `alt_ids` as list of references to Term data structure
- [x] Extract/normalize alt ids from `obonet` and load into terms
- [ ] look into previous sources that might have provided alt ids
- [ ] implications for user interface - any time you put in an identifier, should it get auto-upgraded?
- [ ] implications for oohnana - should the alt id's get auto-upgraded?

**Comment by bgyori** [comment]
OBOs for some of the sources I'm familiar with (e.g., CHEBI, GO) are pretty good with providing alt_ids. For many other sources (e.g., UniProt, HGNC) I implemented custom solutions in INDRA that could be adapted here.

**Comment by cthoyt** [comment]
Yes, this one is a low hanging fruit. The data is already there, I just never added a parser for it. The tricky part will be deciding how to handle alt ids (normalization to standard ID for example)

I think the way you do it in protmapper is a good inspiration
