### ISSUE TITLE
Handle salts in DrugBank

### ISSUE THREAD

**Issue by bgyori** [pyobo/pyobo#80]
DrugBank contains salts for some entries, e.g., for https://go.drugbank.com/drugs/DB00813, there is a corresponding https://go.drugbank.com/salts/DBSALT000301 (on the website, these are listed under Product Ingredients, "Active ingredients including salts and other forms of exact ingredients used in drug products."). Currently the OBO export of DrugBank doesn't contain any of these salts, but xref mappings from e.g., CHEBI provide mappings to these salt forms (see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:31602 under Manual Xrefs) which show up in the ChEBI OBO. It looks like currently there is not identifiers.org entry for the DBSALT name space and these DBSALT IDs are technically invalid under the `drugbank` prefix. Should we add a new entry to the metaregistry for these salts or resolve this in some other way?

**Comment by cthoyt** [comment]
That's a great idea, Ben. I'll make a PR for this

**Comment by cthoyt** [comment]
The PR did most of the work, except dealing with incorrect references in ChEBI. Perhaps the best solution is to petition ChEBI to make some improvements (see https://github.com/ebi-chebi/ChEBI/issues/3932)

The code to get the mappings in a dataframe is:

```python
import pyobo
df = pyobo.get_filtered_relations_df('drugbank', 'obo:has_salt')
```
